### ISSUE TITLE
PEER TO PEER REVIEW

### ISSUE THREAD

**Issue by clintonjosephs** [HAMMAS-SALEEM/Awesome_Books#2]
Hey Hammas 👋 ,

Good job so far on your project, but we noticed a few issues that you would need to look into so that your project would be complete; see below

- To make it readable add easy to debug, create the following function
               -  AddBook()
               - RemoveBook(bookId)
               - DisplayBook()
               - ManipulateLocalStorage()
- In the AddBook Function all you need to do is to "UNSHIFT" and object "{id, title, author} to the booksList array each time the submit button is clicked.
- In the removeBook function all you need do is run an array filter function like below
                    - booksList = booksList.filter((books) => books.id !== bookId); 
                    - then run your displaybook function below it
- DisplayBook function should read the items in the booksList array of objects and append to the ul created in your html file
              - You can refer to https://github.com/omarsalem7/Awesome-books/pull/1  repo for a guide

- Finally, the manipulateLocalstorage function should just call localStorage.setItem('books', JSON.stringify(booksList);

Feel free to reach out if you have any further explanations.

Cheers 😊

**Comment by HAMMAS-SALEEM** [comment]
Thanks for reaching out to me and giving me suggestions about my project. Alhamdulillah, I have implemented all the required changes from you on my project. ✔️ 

Thanks again for raising the issue in my repository. 👍
